sonata_admin:
  title: '%slcorp_admin.dashboard.title%'
  title_logo: '%slcorp_admin.dashboard.logo%'
  persist_filters: true
  options:
    html5_validate: true     # enable or disable html5 form validation
    confirm_exit: true     # enable or disable a confirmation before navigating away
    js_debug: '%env(bool:APP_DEBUG)%'    # enable or disable to show javascript debug messages
    use_icheck: true
#    use_bootlint: '%env(bool:APP_DEBUG)%' # enable
    use_stickyforms: true
    form_type: 'standard'
  global_search:
    empty_boxes: show
    admin_route: show
  show_mosaic_button: false
  breadcrumbs:
    child_admin_route: show
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
  templates:
    layout: '@SlcorpAdmin/standart_layout.html.twig'
    ajax: '@SlcorpAdmin/ajax_layout.html.twig'
    list: '@SlcorpAdmin/CRUD/ajax_list.html.twig'
    pager_results: '@SlcorpAdmin/Pager/results.html.twig'
    edit: '@SlcorpAdmin/CRUD/edit.html.twig'
    dashboard: '@SlcorpAdmin/Core/dashboard.html.twig'

#  assets:
#    stylesheets:
#      - bundles/sonataadmin/app.css
#      - build/vendors-node_modules_tabler_core_dist_css_tabler_css.css
#      - build/app.css
#      - build/sonata.css
##       Отключить при переработке стилей


sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [ admin ]

#DOCUMENTATION
#https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/configuration/