<?php

declare(strict_types=1);

namespace Slcorp\AdminBundle\Infrastructure\Persistence\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250314064909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin_bundle_table_user_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, table_class VARCHAR(255) NOT NULL, table_data JSON NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9DD1BAD8A76ED395 ON admin_bundle_table_user_preference (user_id)');
        $this->addSql('ALTER TABLE admin_bundle_table_user_preference ADD CONSTRAINT FK_9DD1BAD8A76ED395 FOREIGN KEY (user_id) REFERENCES role_model_bundle_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX user_table_class_unique ON admin_bundle_table_user_preference (user_id, table_class)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin_bundle_table_user_preference DROP CONSTRAINT FK_9DD1BAD8A76ED395');
        $this->addSql('DROP TABLE admin_bundle_table_user_preference');
        $this->addSql('DROP INDEX user_table_class_unique');
    }
}
